name: smart_urban_planner
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.0
  fluttertoast: ^8.2.4
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  get: ^4.6.6
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path_android: "assets/smart-urban-planner-logo.png"
  image_path_ios: "assets/smart-urban-planner-logo.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/smart-urban-planner-logo.png"
    background_color: "#hexcode"
    theme_color: "#fffff"
  windows:
    generate: true
    image_path: "assets/smart-urban-planner-logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/smart-urban-planner-logo.png"

flutter:
  uses-material-design: true
